# This is a config synced from dry-rb/template-gem repo

sources:
  - repo: dry-rb/template-gem
    sync:
      - ".action_hero.yml.erb"
      - ".devtools/templates/*.sync:${{dir}}/${{name}}"
      - ".github/**/*.*"
      - "gemspec.erb:dry-monads.gemspec"
      - "spec/support/*"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.md"
      - "LICENSE.erb"
      - "README.md.erb"
      - "Gemfile.devtools"
      - ".rspec"
      - ".rubocop.yml"
  - repo: action-hero/workflows
    sync:
      - ".github/workflows/*.yml"
