inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/integration/either_spec.rb'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/MethodName:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/StabbyLambdaParentheses:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/SymbolProc:
  Exclude:
    # This rule is broken in specs on purpose to make examples clearer
    - 'spec/**/*'

Style/SignalException:
  Exclude:
    - 'spec/**/*'

Style/ModuleFunction:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Metrics/LineLength:
  Max: 110

Style/FileName:
  Exclude:
    - 'lib/dry-monads.rb'

Lint/Debugger:
  Exclude:
    - 'bin/console'

Lint/HandleExceptions:
  Exclude:
    - 'spec/spec_helper.rb'

Security/JSONLoad:
  Exclude:
    - 'spec/**/*'

AllCops:
  TargetRubyVersion: 2.1
