name: dry-monads
codacy_id: f2eed41bf7f04b38b0a7691c2cf6e73c
gemspec:
  authors: ["Nikita Shilnikov"]
  email: ["fg@flashgordon.ru"]
  summary: "Common monads for Ruby"
  runtime_dependencies:
    - [concurrent-ruby, "~> 1.0"]
    - [zeitwerk, "~> 2.6"]
    - [dry-core, "~> 1.0"]
